general {
    layout = dwindle

    allow_tearing = false  # Allows `immediate` window rule to work

    gaps_workspaces = $workspaceGaps
    gaps_in = $windowGapsIn
    gaps_out = $windowGapsOut
    border_size = $windowBorderSize

    col.active_border = $activeWindowBorderColour
    col.inactive_border = $inactiveWindowBorderColour
}

# dwindle {
#     # force_split = 2
# 	# preserve_split = true
# 	# smart_split = false
# 	# smart_resizing = true
# }

master {
    new_on_top = false        # new windows go to bottom of stack (top-to-bottom order)
    mfact = 0.55              # master takes 55% of screen width
    new_status = slave        # new windows open as slaves, not master
    orientation = left        # master on left, stack on right
    smart_resizing = true
}